language: go

# Don't build other branches that are being used for PRs.
# Currently only the master branch is used in this repo.
branches:
  only:
    - master

matrix:
  include:
    - go: 1.6.2

install:
- go get -v ./...

script:
- go test -v ./...
- diff -u <(echo -n) <(gofmt -d -s .)
